mqtt:
  host: homeassistant.stadel15.net
  username: smarthome
  password: smarthome!23
  topic: energyassistant

homeassistant:
  demo_mode: true
  url: https://homeassistant.stadel15.net
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlNTI5NGVkYmUxMWI0NzZiOWFiZDNjZjBkMTAyNzA3MSIsImlhdCI6MTY4NDUyMzIzMSwiZXhwIjoxOTk5ODgzMjMxfQ.cGtRmfbT9hmk-_FwzkTeBRJZ4sJitM8eJixXb0y4NUg

home:
  name: "Stadel 15"
  solar_power: sensor.solaredge_i1_ac_power
  solar_energy: sensor.solaredge_i1_ac_energy_kwh
  grid_supply_power: sensor.solaredge_m1_ac_power
  imported_energy: sensor.solaredge_m1_imported_kwh
  exported_energy: sensor.solaredge_m1_exported_kwh
  devices:
    - name: Keba
      id: 77e0a2d6-1e07-4ec3-91b6-b951a25d7d93
      type: homeassistant
      icon: mdi-car-electric
      power: sensor.keba_charge_power
      energy: sensor.keba_total_charged_energy
    - name: Tumbler
      id: 246e6ffa-f3d1-4294-bd19-8aea1a86e53e
      type: homeassistant
      icon: mdi-tumble-dryer
      power: sensor.tumbler_power
      energy: sensor.laundry_tumbler_energy
      energy_scale: 0.001
    - name: Desk
      id: d2beb996-b410-43ad-ae3f-659310460948
      type: homeassistant
      icon: mdi-desk
      power: sensor.officedesk_power
      energy: sensor.desk_energy
      energy_scale: 0.001
    - name: Rack
      id: 154c4848-f6b9-4bf3-b926-e0152c2c8bac
      type: homeassistant
      icon: mdi-server-network
      power: sensor.rack_power
      energy: sensor.rack_energy
      energy_scale: 0.001
    - name: Warm Wasser
      id: 67ca8a1e-0181-4528-88bf-dabf646c1af2
      type: stiebel-eltron
      state: binary_sensor.stiebel_eltron_isg_is_heating_boiler
      energy_today: sensor.stiebel_eltron_isg_consumed_water_heating_today
      energy_total: sensor.stiebel_eltron_isg_consumed_water_heating_total
      temperature: sensor.stiebel_eltron_isg_actual_temperature_water
    - name: Heizung
      id: 11be2857-1114-4f10-b7d4-7c45b8e58ffc
      type: stiebel-eltron
      state: binary_sensor.stiebel_eltron_isg_is_heating
      energy_today: sensor.stiebel_eltron_isg_consumed_heating_today
      energy_total: sensor.stiebel_eltron_isg_consumed_heating_total
      temperature: sensor.stiebel_eltron_isg_actual_temperature_fek
