device_type:
  manufacturer: v-zug
  model: Adora S
  icon: mdi-dishwasher
  state:
    state_on:
      threshold: 10
    state_off:
      upper: 20
      lower: 15
      for: 1500
      trailing_zeros_for: 720
