name: "Lint and test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.3"

      - name: "Set up Python"
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Run"
        run: python3 -m ruff check .
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v3.5.3"
      - name: Setup Python
        uses: "actions/setup-python@v4.6.1"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Create client folder
        run: mkdir -p client        
      - name: Run tests
        run: |
          pytest \
            -qq \
            --durations=10 \
            -o console_output_style=count \
            -p no:sugar \
            tests
        env:
          APP_CONFIG_FILE: test 
